### ISSUE TITLE
Tests For Indirect Calls

### ISSUE THREAD

**Issue by l-kent** [UQ-PAC/BASIL#110]
It would be good to have the tests that relate to indirect calls be moved to their own set of tests, and have them specifically look at whether indirect calls are resolved correctly or not (not just whether they are resolved at all), using the analysis.

The tests which have indirect calls are the following:
- functionpointer (all variations)
- indirect_call (all variations except the O2 variations)
- jumptable (all except O2)
- jumptable2 (all variations)
- jumptable3 (all clang variations)
- switch2 (clang, clang_no_plt_no_pic, clang_pic)
- syscall (clang_O2)

**Comment by ailrst** [comment]
To implement this I might write a function to query the IL using the visitor, like a genral version of the visitor you wrote to extract the variables without stores and loads https://github.com/UQ-PAC/bil-to-boogie-translator/blob/e0828905663ce6435652e5c90b69abdd4a77596e/src/main/scala/ir/Visitor.scala#L320

Basically a function that takes a predicate on whether to descend into the node, a predicate that matches nodes, 
and a function/closure to apply when the match is satisfied.
