### ISSUE TITLE
DSA overlapping accesses

### ISSUE THREAD

**Issue by sadrabt** [UQ-PAC/BASIL#254]
DSA should be able to recognize and overlapping access. (ie if two addresses are read into 128 bit register, stored in  memory and then accessed separately).
https://github.com/UQ-PAC/BASIL/pull/222#issuecomment-2337117908 

R31 + 0x10 refers to a stack element node with two cells. One at offset 0 (R31 + 0x10) and one at offset 8(R31 + 0x18).
The issue here is that the analysis doesn't merge the cell for add_six with the second cell in of R31 + 0x10 node since it can't yet tell the 128 bit reads add_six as well as add_two.

Each global is represented using separate node. the analysis currently merges add_two's node with the node of the stack position. 

On possibility would be to represent globals that have overlapping accesses as one node. similar to the stack.  ( i think this is only safe if we we can find all the accesses to the globals to soundly do this) however unlike the stack we can't find all accesses locally (even indirect stack references can't be found without a pointer analysis). Alternatively we can group consecutive globals into one node.

```000003fe: R8 := 0x10000
// 0x10DC0 contains a pointer to the procedure add_two
// 0x10DC8 contains a pointer to the procedure add_six
00000404: R8 := R8 + 0xDC0
// loading 128 bits from 0x10DC0 loads both the 64-bit pointer at address 0x10DC0
// and the 64-bit pointer at address 0x10DC8 to V0, concatenated together
0000040b: V0 := mem[R8, el]:u128
// storing V0 to the stack stores the pointer to add_two at R31 + 0x10 and the pointer to add_six at R31 + 0x18
00000413: mem := mem with [R31 + 0x10, el]:u128 <- V0
0000041a: R8 := mem[R8 + 0x10, el]:u64
00000422: mem := mem with [R31 + 0x20, el]:u64 <- R8
00000429: R8 := mem[R31 + 0x10, el]:u64
0000042e: R30 := 0x7D0
00000431: call R8 with return %00000433

00000433:
// the DSA says that R8 at this assignment points to node 434 which is empty, but it should point to add_six
// or alternatively some node that represents that the pointers to add_two and add_six were loaded together and stored on the stack together
00000438: R8 := mem[R31 + 0x18, el]:u64
0000043d: R30 := 0x7D8
00000440: call R8 with return %00000442
```

**Comment by sadrabt** [comment]
indirect overlapping accesses are also an issue: 


```
R0 = G + 8  // where G is base address for the heap
R1 = G + 12 // two consecutive globals
R2 = Malloc()
*R2 = R0 // 64 bit write
R3 = *R2  // 64 bit read
R4 = *R3 // 128 bit read
```

**Comment by l-kent** [comment]
It's not going to work to try to detect these accesses before the DSA. You will need a way of checking if an access is accessing multiple nodes simultaneously in this way so they can be concatenated and merged.

**Comment by l-kent** [comment]
I don't think your pseudocode is the clearest example. Global variables aren't on the heap, so the base address of the heap isn't relevant, and the global variable with address G + 8 is only 32 bits, so even a 64-bit access to it would also access the global variable at G + 12

**Comment by sadrabt** [comment]
yeah my example is not great. I confused myself a little while thinking about the heap objects. since what you suggested can be done for stack and globals where the adjacent  node is known. can check if what is being accessed is stack or global (or both if they have been unified prior) and do the merge. But it doesn't make a lot of sense for the heap objects. one possibility is to expand the heap nodes like we do now to accommodate the access regardless of its size. This is similar to if we have malloc and access outside of the allocated size of the memory block. 

currently the analysis expands the malloc. The analysis will know what address R1 holds with respect to the malloc base.
if malloc creates a new node M. R0 -> (M, 0) and R1 -> (M,32). 
However, the analysis won't be able to tell if writes to R1 will change the contents of another object in memory 
```
R0 = Malloc(16)
R1 = R0 + 32
```

**Comment by l-kent** [comment]
You don't need to worry about this sort of case for heap objects - if you access out of the allocated size of the heap object, you don't know what will be accessed (most likely is it causes a segfault), so there should be some sort of collapse of the node. This is not a case that will be encountered in code that is working correctly.
